import type { Company } from '@/types';

const COMPANIES: Record<string, Company> = {
  '890903938': {
    nit: '890903938',
    razon_social: 'BANCOLOMBIA S.A.',
    estado: 'ACTIVA',
    municipio: 'Medellín',
    departamento: 'Antioquia',
    actividad_principal: 'Actividades de banca comercial',
    codigo_ciiu: '6412',
    fecha_matricula: '1945-01-15',
    ultima_renovacion: '2026-01-20',
    tipo_sociedad: 'Sociedad Anónima',
    camara: 'Cámara de Comercio de Medellín para Antioquia',
    estado_renovacion_2024: 'RENOVADA',
    tamano: 'GRANDE',
    empleados_rango: 'Más de 200',
    responsabilidades_tributarias: [
      'IVA',
      'Retención en la Fuente',
      'Impuesto sobre la Renta y Complementarios',
      'Gran Contribuyente',
      'ICA',
    ],
    tiene_comercio_exterior: true,
    tipo_comercio: 'importador',
  },
  '860034313': {
    nit: '860034313',
    razon_social: 'ECOPETROL S.A.',
    estado: 'ACTIVA',
    municipio: 'Bogotá',
    departamento: 'Bogotá D.C.',
    actividad_principal: 'Extracción de petróleo crudo',
    codigo_ciiu: '0610',
    fecha_matricula: '1951-08-25',
    ultima_renovacion: '2026-02-15',
    tipo_sociedad: 'Sociedad Anónima',
    camara: 'Cámara de Comercio de Bogotá',
    estado_renovacion_2024: 'RENOVADA',
    tamano: 'GRANDE',
    empleados_rango: 'Más de 200',
    responsabilidades_tributarias: [
      'IVA',
      'Retención en la Fuente',
      'Impuesto sobre la Renta y Complementarios',
      'Autoretenedor',
    ],
    tiene_comercio_exterior: true,
    tipo_comercio: 'exportador',
  },
  '890900608': {
    nit: '890900608',
    razon_social: 'ALMACENES ÉXITO S.A.',
    estado: 'ACTIVA',
    municipio: 'Envigado',
    departamento: 'Antioquia',
    actividad_principal: 'Comercio al por menor en establecimientos no especializados',
    codigo_ciiu: '4711',
    fecha_matricula: '1949-05-20',
    ultima_renovacion: '2026-01-08',
    tipo_sociedad: 'Sociedad Anónima',
    camara: 'Cámara de Comercio de Medellín para Antioquia',
    estado_renovacion_2024: 'RENOVADA',
    tamano: 'GRANDE',
    empleados_rango: 'Más de 200',
    responsabilidades_tributarias: [
      'IVA',
      'Retención en la Fuente',
      'Impuesto sobre la Renta y Complementarios',
      'Gran Contribuyente',
    ],
    tiene_comercio_exterior: false,
  },
  '800197268': {
    nit: '800197268',
    razon_social: 'AVIANCA S.A.',
    estado: 'ACTIVA',
    municipio: 'Bogotá',
    departamento: 'Bogotá D.C.',
    actividad_principal: 'Transporte aéreo regular de pasajeros',
    codigo_ciiu: '5111',
    fecha_matricula: '1919-12-05',
    ultima_renovacion: '2025-01-12',
    tipo_sociedad: 'Sociedad Anónima',
    camara: 'Cámara de Comercio de Bogotá',
    estado_renovacion_2024: 'RENOVADA',
    tamano: 'GRANDE',
    empleados_rango: 'Más de 200',
    responsabilidades_tributarias: [
      'IVA',
      'Retención en la Fuente',
      'Impuesto sobre la Renta y Complementarios',
    ],
    tiene_comercio_exterior: true,
    tipo_comercio: 'exportador',
  },
  '900123456': {
    nit: '900123456',
    razon_social: 'EMPRESA EJEMPLO PYME SAS',
    estado: 'ACTIVA',
    municipio: 'Barranquilla',
    departamento: 'Atlántico',
    actividad_principal: 'Actividades de consultoría de gestión empresarial',
    codigo_ciiu: '7020',
    fecha_matricula: '2015-06-10',
    ultima_renovacion: '2025-06-20',
    tipo_sociedad: 'Sociedad por Acciones Simplificada',
    camara: 'Cámara de Comercio de Barranquilla',
    estado_renovacion_2024: 'RENOVADA',
    tamano: 'PEQUEÑA',
    empleados_rango: '11-50',
    responsabilidades_tributarias: [
      'IVA',
      'Retención en la Fuente',
      'Impuesto sobre la Renta y Complementarios',
      'ICA',
    ],
    tiene_comercio_exterior: false,
  },
  '900234567': {
    nit: '900234567',
    razon_social: 'STARTUP TECH SOLUTIONS SAS',
    estado: 'ACTIVA',
    municipio: 'Barranquilla',
    departamento: 'Atlántico',
    actividad_principal: 'Desarrollo de software a medida y otros programas informáticos',
    codigo_ciiu: '6201',
    fecha_matricula: '2019-03-15',
    ultima_renovacion: '2024-03-20',
    tipo_sociedad: 'Sociedad por Acciones Simplificada',
    camara: 'Cámara de Comercio de Barranquilla',
    estado_renovacion_2024: 'VENCIDA',
    tamano: 'MICROEMPRESA',
    empleados_rango: '1-10',
    responsabilidades_tributarias: [],
    tiene_comercio_exterior: false,
  },
  '900111111': {
    nit: '900111111',
    razon_social: 'COMERCIALIZADORA CARIBE SAS',
    estado: 'ACTIVA',
    municipio: 'Barranquilla',
    departamento: 'Atlántico',
    actividad_principal: 'Comercio al por mayor de productos alimenticios, bebidas y tabaco',
    codigo_ciiu: '4631',
    fecha_matricula: '2010-09-22',
    ultima_renovacion: '2026-02-01',
    tipo_sociedad: 'Sociedad por Acciones Simplificada',
    camara: 'Cámara de Comercio de Barranquilla',
    estado_renovacion_2024: 'RENOVADA',
    tamano: 'MEDIANA',
    empleados_rango: '51-200',
    responsabilidades_tributarias: [
      'IVA',
      'Retención en la Fuente',
      'Impuesto sobre la Renta y Complementarios',
      'ICA',
    ],
    tiene_comercio_exterior: false,
  },
};

export function getCompany(nit: string): Company | null {
  return COMPANIES[nit] ?? null;
}

export function listNITs(): string[] {
  return Object.keys(COMPANIES);
}
